# Site settings
title: Axon Framework
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Axon Framework is tha bomb! developer support and enterprise support options available.
baseurl: "/pages-trial/" # the subpath of your site, e.g. /blog/
url: "http://axonframework.org" # the base hostname & protocol for your site
twitter: https://twitter.com/axonframework
github:  https://github.com/axonframework
youtube:  https://www.youtube.com/playlist?list=PLnwrDvSv4WM-yk-IgdDOlQxkF0_wCd0Sh
#google_play: ''
#google_plus_com: '00000'  # Community link
#google_plus_per: ''  #Personal link
#facebook_app_id:

# Layout settings
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

mainnav:
  option1:
    name: Axon Framework
    link: index
  option2:
    name: Services
    link: services
  option3:
    name: Explore
    link: explore
  option4:
    name: Community
    link: community
  option5:
    name: Blog
    link: blog
  option6:
    name: Axon Platform
    link: platform

disqus: true
disqus_shortname: 'disqusname'

# Build settings
markdown: kramdown

gems:
  - jemoji
highlighter: rouge
